### ISSUE TITLE
list of features

### ISSUE THREAD

**Issue by tonymj76** [BuildForSDG/good-health-client#3]
create a list of features for the solution being built

**Comment by elizabethadegbaju** [comment]
There has not been any conclusion on the discussion of the app's functionalities, what features are we talking about.

**Comment by elizabethadegbaju** [comment]
Attached herewith is the product backlog
[backlog.docx](https://github.com/BuildForSDG/good-health-client/files/4577514/backlog.docx)

**Comment by tonymj76** [comment]
Nice work
